version: '3.8'

services:
  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack-server
    ports:
      - "6379:6379"  # Port kết nối cho Spring Boot
      - "8001:8001"  # Port cho giao diện RedisInsight (Web UI)
#    environment:
#      - REDIS_ARGS=--requirepass "YourSecurePassword" --appendonly yes
    volumes:
      - redis-stack:/data
    restart: always
volumes:
  redis-stack:
