services:
  postgresql:
    image: postgres:15
    environment:
      POSTGRES_DB: volunteerhub
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5431:5432"
    volumes:
      - postgres_sql:/var/lib/postgresql/data
volumes:
  postgres_sql: